### ISSUE TITLE
Problemas al desplegar

### ISSUE THREAD

**Issue by jualorper** [Decide-Palkia/decide#101]
Al hacer pull de la rama voting-develop (commit ca1442949d7569d0d1b9f02cba5a2262d1e2658e), al intentar desplegar aparece el error "ModuleNotFoundError: No module named 'apscheduler'". Tras instalar este modulo via pip, aparece otro error "ModuleNotFoundError: No module named 'scheduler.urls'".

**Comment by angel96** [comment]
Arreglado con exito el error. Se encuentra el fichero en la rama voting-develop. Commit (Merge) que referencia [e570941](https://github.com/Decide-Palkia/decide/commit/e5709419ac648c2470340160b1766d68cba8c7c8). Cierro la issue en consecuencia.
