### ISSUE TITLE
None al recuperar candidatura de votación

### ISSUE THREAD

**Issue by Yerehia** [Decide-Palkia/decide#103]
Si se crea una votación **manualmente** desde la base de datos:

# Votación
![Votacion](https://i.ibb.co/VH2yTc7/Sin-t-tulo3.png)

# Candidatura
![Candidatura](https://i.ibb.co/PCxQjbT/Sin-t-tulo5.png)

# Pub_key
![Pub_key](https://i.ibb.co/SwtYpcn/Sin-t-tulo6.png)

# Tabla relacional votación y candidatura
![Tabla relacional](https://i.ibb.co/K50qW1r/Sin-t-tulo4.png)

Y posterioremente intentamos recuperar en python (django)

![](https://i.ibb.co/cX8Qj76/pantallazo.png)

El objeto votación y candidatura por separado, ambos han sido guardados correctamente, pero al acceder a la candidatura a través de la votación, devuelve un objeto None

![](https://i.ibb.co/x3zf45B/pantallazo2.png)

**Comment by manelcecs** [comment]
Buenas, voy a intentar resolverlo de un modo sencillo.
Para acceder a los valores de las tablas intermedias hay que seguir el mismo formato que al hacer la consulta a la BBDD.
En concreto, en este caso sería: `voting.candidatures.all()`
Haz la prueba, si aún así te da fallo, investigaremos, pero al ser un fallo de sintaxis, probamos primero esto.

**Comment by Yerehia** [comment]
Muchas gracias, ya podemos acceder a las nuevas candidaturas correctamente. Se lo comunico a mis demás compañeros de cabina para continuar con la integración.

Procedo al cierre de la issue.
