### ISSUE TITLE
Problema detectado con el planificador implementado por votación

### ISSUE THREAD

**Issue by DaviidGilB** [Decide-Palkia/decide#113]
Hemos detectado el siguiente problema causado por el planificador:

![image](https://user-images.githubusercontent.com/24230787/72172543-b8d15a80-33d5-11ea-9f81-025bb4b7f52f.png)

Solicitamos a votación una solución con este error.

**Comment by angel96** [comment]
Prueba con las siguientes lineas de codigo que te remito para tu settings.py (en el modulo central - decide)

> import os
> os.environ['TZ']='Europe/Madrid'

**Comment by DaviidGilB** [comment]
Gracias por la solución.
