### ISSUE TITLE
Error(IndexError) en: /census/web/add/{id_votacion}

### ISSUE THREAD

**Issue by falkbn** [Decide-Palkia/decide#129]
Error capturado usando entorno virtual y firefox.
Pasaos para reproducirlo:
1. Crear una votacion y mirar su id.
2. Acceder a  /census/web/add/{id_votacion} usando el mismo id.

Adjunto captura:
![image](https://user-images.githubusercontent.com/43813098/72203805-08189900-3471-11ea-8c50-a09b114b4d42.png)

**Comment by falkbn** [comment]
Es obvio a si que lo he omitido, pero logeate con una cuenta de administrador para poder reproducir los pasos

**Comment by a8081** [comment]
Solucionado
![Screenshot from 2020-01-11 17-58-10](https://user-images.githubusercontent.com/38320652/72207749-1af49300-349c-11ea-84b0-020bc1750d5d.png)
