### ISSUE TITLE
Bug con la url personalizada

### ISSUE THREAD

**Issue by jualorper** [Decide-Palkia/decide#133]
Al crear una votación y dejamos en blanco el campo de la url personalizada, no hay ningún problema. Lo hay al crear una segunda votación y dejar ese campo en blanco. Entonces salta el siguiente error:
![image](https://user-images.githubusercontent.com/35260622/72207333-80468500-3498-11ea-9b5c-88ea16497d2c.png)

**Comment by angel96** [comment]
Fallo en el modelo. Detecta que al haber una votación nula, la siguiente si la dejas igual da conflicto. Quitar unique=true del modelo. Se habilitara un mecanismo de unicidad para asegurar que se crea correctamente la votación.

**Comment by angel96** [comment]
Arreglado el fallo.
