### ISSUE TITLE
Ejercicio de propuesta de cambio 

### ISSUE THREAD

**Issue by andddommon** [Decide-Palkia/decide#143]
Se presentará un ejercicio con una propuesta concreta de cambio en la que a partir de un cambio que se requiera, se expliquen paso por paso (incluyendo comandos y uso de herramientas) lo que hay que hacer para realizar dicho cambio. 

https://github.com/EGCETSII/Entregables/wiki/Documento-del-proyecto#ejercicio-de-propuesta-de-cambio

**Comment by Pabloreneses98** [comment]
Terminada y subida a la wiki correctamente.
