### ISSUE TITLE
Conclusiones y trabajo futuro

### ISSUE THREAD

**Issue by andddommon** [Decide-Palkia/decide#144]
se enunciarán algunas conclusiones y se presentará un apartado sobre las mejoras que se proponen para el futuro (curso siguiente) y que no han sido desarrolladas en el sistema que se entrega
https://github.com/EGCETSII/Entregables/wiki/Documento-del-proyecto#conclusiones-y-trabajo-futuro

**Comment by Pabloreneses98** [comment]
Completado y subido a la parte de Documentación de la wiki.
