### ISSUE TITLE
Generar solicitud de datos de censo

### ISSUE THREAD

**Issue by Yerehia** [Decide-Palkia/decide#32]
Se requiere generar una solicitud en la que se reflejen los datos que se necesitan para el filtrado y visualización de los resultados y mandarla al equipo responsable del censo.

**Comment by jmsx** [comment]
Se han generado los cambios solicitados, para acceder a la información adicional se debe realizar mediante la propiedad perfil. Por ejemplo:
`User.perfil.sexo`
