### ISSUE TITLE
Creación del modelo de candidatos y candidaturas

### ISSUE THREAD

**Issue by angel96** [Decide-Palkia/decide#37]
### Introducción
---
Se deberá crear el modelo correspondiente a los candidatos y candidatas desde la interfaz del administrador.

Teniendo en cuenta que un candidato y una candidatura deberá tener los siguientes atributos:

**Candidatura**
Nombre
Lista de candidatos

**Candidato**
Nombre
Tipo (Presidente o diputado)
Provincia_Nacimiento
Provincia_DondeVive
¿Primarias?
Sexo

Todo candidato deberá estar adscrito a al menos una candidaturas.

Su creación deberá tener en cuenta los siguientes requisitos:

- R02 -  Habrá dos tipos de candidatos/as. Quienes concurran como candidatos/as a la presidencia del gobierno y quienes concurran como candidatos al congreso

**Comment by jualorper** [comment]
Considero que los siguientes atributos del modelo de candidato no podrían ser null o blank:

- name
- type
- born_area
- current_area
- primaries
- sex

Por otro lado, current_area y born_area quizás debería ser un enumerado de las provincias.

**Comment by angel96** [comment]
Estoy de acuerdo. Aunque, deberiamos contemplar la opcion de considerar las areas de nacimiento y ciudad como una tabla independiente. Por eso de que esta característica fuera modificable a nivel de usuario. Creo que seria cuestión de investigar algun modelo de tabla ya hecho con todas las ciudades necesarias.
