### ISSUE TITLE
Normalizacion de estilos

### ISSUE THREAD

**Issue by jmsx** [Decide-Palkia/decide#55]
Normalizacion de estilos entre las vistas de los distintos módulos.

**Comment by JoseAFerrete** [comment]
Normalizando los estilos entre cabina (booth) y censo (census).
El estilo no está definido del todo aún, de momento se han puesto en común colores de cabecera y fondo, así como sus fuentes.

**Comment by JoseAFerrete** [comment]
Se han coordinado de forma general los estilos de toda la plataforma, incluyendo:

*Estilo de la cabecera.
*Contenido de la cabecera.
*Contenido de la barra de navegación.
