### ISSUE TITLE
Bug en la validación al importar candidatos

### ISSUE THREAD

**Issue by davcamalv** [Decide-Palkia/decide#60]
En las candidaturas para el congreso debe haber al menos 2 personas por provincia que hayan nacido en dicha provincia o tengan allí su lugar de residencia. Sin embargo, si un candidato nació en el mismo lugar en el que reside, actualmente supera la validación, aun siendo únicamente una persona y no dos. El requisito se implementó en la issue #56. Versión de firefox 71.0.

**Comment by jualorper** [comment]
Incidencia aceptada.
