### ISSUE TITLE
Solicitud a cabina del estilo usado

### ISSUE THREAD

**Issue by jualorper** [Decide-Palkia/decide#82]
Desde el modulo de votación solicitamos al módulo cabina el estilo que va a usar para adaptarlo a nuestro modulo y que la aplicación tenga un estilo uniforme. Se espera recibir uno o varios archivo css/js o un enlace en su defecto.

**Comment by mc-arenas** [comment]
Actualmente el estilo del index, login y registro se encuentra en la rama booth-principal. En esa rama podéis encontrar los enlaces de bootstrap empleados, y la forma en la que se ha organizado.
