### ISSUE TITLE
bug en postproc/views.py, en el algoritmo paridad

### ISSUE THREAD

**Issue by rojas77** [Decide-Palkia/decide#83]
cuando se están asignado los escaños a hombres y mujeres no se tiene en cuenta que alguna de las listas se pueda acabar antes de que estén todos los escaños asignados.

**Comment by jossouvil** [comment]
Solucionado, ahora si se cumple el 40-60 pero se da el caso de que se acaba los candidatos de un grupo ahora completara la lista con solo los del otro.
