### ISSUE TITLE
Resolver problema de integración con los algortimos DHONDT y SIMPLE

### ISSUE THREAD

**Issue by rojas77** [Decide-Palkia/decide#84]
Cuando se haga la asignación de escaños a los candidatos los test de DHONDT y SIMPLE fallaran porque el resultado no será el mismo, ya que estos solo asignan escaños a partidos

**Comment by jossouvil** [comment]
Solucionado, se ha realizado una solución alternativa para no tener que reestructurar todos los test que consiste en el llamado individual de algoritmos, en lugar de interconectarlos de forma fija.
