### ISSUE TITLE
Test test_paridad4 falla

### ISSUE THREAD

**Issue by jossouvil** [Decide-Palkia/decide#91]
[log.pdf](https://github.com/Decide-Palkia/decide/files/4030418/log.pdf)

**Comment by jossouvil** [comment]
Ademas, es un test acerca de simple sin paridad así que el nombre del test debería de ser cambiado.

**Comment by jossouvil** [comment]
ahora ha cambiado el error a que no devuelve el dato esperado.
[log.pdf](https://github.com/Decide-Palkia/decide/files/4030648/log.pdf)

**Comment by rojas77** [comment]
ya se arregló el test, los datos estaban mal ordenados
