### ISSUE TITLE
Renombramiento de test

### ISSUE THREAD

**Issue by jossouvil** [Decide-Palkia/decide#94]
La mayoría de test tienen títulos que no representa del todo lo que están probando. Opino que seria buena practica renombrarlos para que sigan el formato test_[método al que llaman][numero de test] de esta forma serán mas identificables.

**Comment by rojas77** [comment]
Me parece correcto, así será más fácil identificar los errores si no pasan los test

**Comment by rojas77** [comment]
ya se han renombrado los test
