### ISSUE TITLE
Arreglar desplegable en "/census/web"

### ISSUE THREAD

**Issue by falkbn** [Decide-Palkia/decide#97]
El desplegable no funciona correctamente en el enlace: "http://censusfeature.herokuapp.com/census/web/".

![image](https://user-images.githubusercontent.com/43813098/71920256-ae6d5180-3186-11ea-871d-05cc3408ce10.png)

El desplegable aparece dos veces usando Chrome y usando un tamaño de ventana de la mitad del monitor (falla el responsive).

**Comment by JoseAFerrete** [comment]
Con el rediseño de la barra de navegación se ha corregido el bug.

Gracias! :)
